"""
gen_test_data.py
================
用 PC 预处理公式生成 INT8 输入数据，输出为 C 头文件。
编译进 ESP32 可直接测试模型推理，跳过 JPEG 解码和预处理。

用法:
    python gen_test_data.py

输出:
    main/test_inputs.h  — 包含 t1/t2/t3/t4 的 INT8 输入数据
"""

import numpy as np
from PIL import Image
import os

IMG_DIR = "main"
IMG1 = "t1.jpg"
IMG2 = "t2.jpg"
IMG3 = "t3.jpg"
IMG4 = "t4.jpg"

MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)
SCALE = 0.015625  # 2^(-6)，与模型 exponent=-6 一致
TARGET_SHORT = 256
TARGET_SIZE = 224


def preprocess(image_path):
    """与 verify_model.py 完全一致的预处理 — 输出 NHWC INT8"""
    img = Image.open(image_path).convert("RGB")
    w, h = img.size
    if w < h:
        new_w, new_h = TARGET_SHORT, int(h * TARGET_SHORT / w)
    else:
        new_w, new_h = int(w * TARGET_SHORT / h), TARGET_SHORT
    img = img.resize((new_w, new_h), Image.BILINEAR)
    left = (new_w - TARGET_SIZE) // 2
    top = (new_h - TARGET_SIZE) // 2
    img = img.crop((left, top, left + TARGET_SIZE, top + TARGET_SIZE))

    pixels = np.array(img, dtype=np.float32)  # [H, W, C]
    pixels /= 255.0
    pixels = (pixels - MEAN) / STD
    pixels = pixels / SCALE
    pixels = np.round(pixels).clip(-128, 127).astype(np.int8)  # [H, W, C] NHWC
    return pixels


def to_c_array(arr, name):
    """numpy array → C 数组声明"""
    flat = arr.flatten()
    lines = [f"// shape: {list(arr.shape)}"]
    lines.append(f"static const int8_t {name}[] = {{")
    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        lines.append("  " + ", ".join(f"{v:4d}" for v in chunk) + ",")
    lines.append("};")
    lines.append(f"static const int {name}_size = sizeof({name});")
    return "\n".join(lines)


def main():
    print("Generating test input data...")
    t1 = preprocess(os.path.join(IMG_DIR, IMG1))
    t2 = preprocess(os.path.join(IMG_DIR, IMG2))
    t3 = preprocess(os.path.join(IMG_DIR, IMG3))
    t4 = preprocess(os.path.join(IMG_DIR, IMG4))

    print(f"t1 shape: {t1.shape}, range: [{t1.min()}, {t1.max()}]")
    print(f"t2 shape: {t2.shape}, range: [{t2.min()}, {t2.max()}]")
    print(f"t3 shape: {t3.shape}, range: [{t3.min()}, {t3.max()}]")
    print(f"t4 shape: {t4.shape}, range: [{t4.min()}, {t4.max()}]")
    print(f"  t1 ch0[0..3]: {t1[0, :4, 0].tolist()}")
    print(f"  t2 ch0[0..3]: {t2[0, :4, 0].tolist()}")
    print(f"  t3 ch0[0..3]: {t3[0, :4, 0].tolist()}")
    print(f"  t4 ch0[0..3]: {t4[0, :4, 0].tolist()}")

    content = f"""// Auto-generated by gen_test_data.py
// PC-preprocessed INT8 inputs for model testing (NHWC layout)
#ifndef TEST_INPUTS_H
#define TEST_INPUTS_H

#include <stdint.h>

{to_c_array(t1, "test_input_t1")}

{to_c_array(t2, "test_input_t2")}

{to_c_array(t3, "test_input_t3")}

{to_c_array(t4, "test_input_t4")}

#endif // TEST_INPUTS_H
"""
    out_path = os.path.join(IMG_DIR, "test_inputs.h")
    with open(out_path, "w") as f:
        f.write(content)
    print(f"\nWritten to {out_path}")


if __name__ == "__main__":
    main()
